#------------------------------------------------------------------------------
# QEMU OpenTitan CI
#------------------------------------------------------------------------------

build-clang:
  tags:
    - qemu_ot
  stage: build
  # build QEMU for OT platforms, ensure subprojects are cleaned up first
  # store generated header files and ninja command file as artifacts, which are
  # required to run the clang-tidy stage
  # libvhost-user.c generates sign-compare warnings with clang, so disable
  # warning-as-error
  # the alternative would be to build here with GCC, then rebuild everything
  # with clang in clang-tidy stage, as meson generates different, incompatible
  # warning list between GCC and clang...
  script:
    - rm -rf build
    - git clean -dffx subprojects
    - mkdir build
    - cd build
    - ../configure --cc=clang-19 --disable-werror $QEMU_BUILD_OPTS
        --target-list=riscv32-softmmu,riscv64-softmmu,x86_64-linux-user
    - ninja
    - ninja qemu-img
    - strip qemu-system-riscv32 qemu-img
    - QEMU_DIR="$(cd .. && pwd -P)"; cat compile_commands.json |
        sed -E 's,'"$QEMU_DIR"',@QEMU_DIR@,g' > compile_commands.json.tpl
    - ../scripts/opentitan/swexit.py -t ibexdemo -b 0x0 -o exit_id.bin
    - ../scripts/opentitan/swexit.py -t earlgrey -b 0x80 -o exit_eg.bin
  artifacts:
    public: false
    expire_in: 1 hour
    name: "qemu-ot"
    paths:
      - subprojects/libtomcrypt/src/headers/*.h
      - build/*.h
      - build/qapi/*.h
      - build/trace/*.h
      - build/config.status
      - build/compile_commands.json.tpl
      - build/qemu-system-riscv32
      - build/qemu-img
      - build/exit_*.bin

build-gcc:
  tags:
    - qemu_ot
  stage: build
  # build QEMU for OT platforms, ensure subprojects are cleaned up first
  # build with GCC may need different warnings
  script:
    - rm -rf build-gcc
    - mkdir build-gcc
    - cd build-gcc
    - ../configure --cc=gcc $QEMU_BUILD_OPTS --target-list=riscv32-softmmu,riscv64-softmmu
    - ninja

format:
  tags:
    - qemu_ot
  stage: build
  script:
    - scripts/opentitan/ot-format.sh --ci --Werror --dry-run

tidy:
  tags:
    - qemu_ot
  stage: build
  needs: ["build-clang"]
  script:
    - QEMU_DIR="$(pwd -P)"; cat build/compile_commands.json.tpl |
        sed -E 's,@QEMU_DIR@,'"$QEMU_DIR"',g' > build/compile_commands.json
    - scripts/opentitan/ot-tidy.py --build-dir build --ci-files -j
